            - name: GitHub Action for Android Lint
  # You may pin to the exact commit or the version.
  # uses: yutailang0119/action-android-lint@bd0b5a7d2cc453d16080b90e2a975d4af4aa9588
  uses: yutailang0119/action-android-lint@v4.0.0
  with:
    # The lint report file path. Support glob patterns. e.g `build/reports/*.xml`
    report-path: 
    # Indicates whether to follow symbolic links
    follow-symbolic-links: # optional, default is true
    # Ignore Lint Warnings
    ignore-warnings: # optional, default is false
          
